services:
  php:
    container_name: php-symfony
    restart: always
    build:
      context: ./docker/php
    volumes:
      - ./my_project_directory:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db

  nginx:
    container_name: nginx-symfony
    image: nginx:alpine
    restart: always
    volumes:
      - ./my_project_directory:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  db:
    container_name: db-symfony
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql  # <-- this line mounts a volume
  phpmyadmin:
    container_name: phpmyadmin-symfony
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"  # Access phpMyAdmin at http://localhost:8081
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
  mailhog:
    container_name: mailhog-symfony
    image: mailhog/mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
